version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - '5432:5432' 
    environment:
      POSTGRES_USER: jing
      POSTGRES_PASSWORD: 123qwe!@#
      POSTGRES_DB: database
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: . # Build the API from the current directory
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://jing:123qwe%21%40%23@localhost:5432/database
    volumes:
      - .:/usr/src/api 

volumes:
  pgdata:

